version: '3.4'
services:
  explorer-admin:
    container_name: stats-collector
    image: "stats-collector:${TAG:-latest}"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MAIN_DATA_DIR:-./data}:/skale-stats-collector/data
    networks:
      - metrics_net
    command: "python src/collector/main.py"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - metrics_net
    ports:
      - "3306:3306"

  stats-api:
    container_name: stats-collector-api
    image: "stats-collector-api:${TAG:-latest}"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: core/api/app.py
      FLASK_APP_HOST: ${FLASK_APP_HOST:-0.0.0.0}
      FLASK_APP_PORT: ${FLASK_APP_PORT:-5000}
      FLASK_HOST_PORT: ${FLASK_HOST_PORT:-3009}
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MAIN_DATA_DIR:-./data}:/skale-stats-collector/data
    ports:
      - "${FLASK_HOST_PORT:-3009}:${FLASK_APP_PORT:-5000}"
    command: "python src/api/app.py"

volumes:
  mysql_data:

networks:
  metrics_net:
    driver: bridge